name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots -f ./anotherdaily/pom.xml verify
    - name: compile into war-file
      run: mvn compile war:war -f ./anotherdaily/pom.xml
    - run: mkdir ./anotherdaily/staging && cp ./anotherdaily/target/*.war ./anotherdaily/staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ./anotherdaily/staging
    - uses: actions/download-artifact@v2
      with:
        name: Package
        path: ./anotherdaily/target 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - run: pwd
    - run: ls -a
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bektair/anotherdaily
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

